[tool.poetry]
name = "morphology_gnn"
version = "0.1.0"
description = "GNN for molecular property prediction in morphology."
authors = ["clint <clinthoeselvan@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
torch = "^2.6.0"
torch-geometric = "^2.6.0"
scipy = "^1.16.3"
numpy = "^2.2.6"

[build-system]
requires = ["setuptools>=65.0", "wheel", "pybind11", "torch>=2.6.0"]
build-backend = "setuptools.build_meta"
